### ISSUE TITLE
Establish a Deployment Environment

### ISSUE THREAD

**Issue by jonathanwmendez** [chingu-voyages/v49-tier2-team-18#28]
**__Task Description__**
Describe the task to be completed.

Decide of a deployment environment that will work well with our API key. Best to have a couple of options during our team meeting.

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

Grow API Key

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by Sushmita-Ghosh** [comment]
Explored Vercel as an option - deployed main branch to Vercel-  For now the app is available here:  https://color-picker-project-omega.vercel.app/

For some alternative options -  I have Render & Netlify in mind.
