### ISSUE TITLE
Add Nav Background Color

### ISSUE THREAD

**Issue by BrianSlaby** [chingu-voyages/v49-tier2-team-18#40]
**__Task Description__**
Nav links after expanding hamburger menu at smaller screen sizes need a background color.
This was changed to transparent recently, but this creates awkward text overlap with hero section.
See screenshot below.
Note that this would essentially create a sidebar for the nav links that would obscure text in the hero section.
Maybe that's fine, but maybe we could consider pushing the hero text down below the expanded nav options?

**__Screenshot__**
<img width="448" alt="image" src="https://github.com/chingu-voyages/v49-tier2-team-18/assets/106836794/ffe47e37-91ca-454c-b42e-cad8878c2e73">

**Comment by TanutsaponJ** [comment]
I'm currently working on the task of adding a background color to the nav links after expanding the hamburger menu at smaller screen sizes. This change will help to prevent awkward text overlap with the hero section. I am also considering the option of pushing the hero text down below the expanded nav options to create a clearer separation. Everything should be done by Monday.
