### ISSUE TITLE
Team Member Information Submission: Please Provide Your Details

### ISSUE THREAD

**Issue by TanutsaponJ** [chingu-voyages/v49-tier2-team-18#56]
### Name:
[Enter Name]

### Role:
[Enter Role]

### Photo:
![Profile Picture](https://i.pinimg.com/736x/58/7b/57/587b57f888b1cdcc0e895cbdcfde1c1e.jpg)

### LinkedIn Profile:
[LinkedIn URL]

### GitHub Profile:
[GitHub URL]

**Comment by BrianSlaby** [comment]
**Name**:
Brian Slaby

**Role**:
Web Developer

**Photo**:
I don't really have a "normal" headshot, lol.
![image](https://github.com/chingu-voyages/v49-tier2-team-18/assets/106836794/399ec470-2676-4a75-b904-7d8de95b3bba)

**LinkedIn Profile**:
[https://www.linkedin.com/in/brian-slaby-78022388/](https://www.linkedin.com/in/brian-slaby-78022388/)

**GitHub Profile**:
[https://github.com/BrianSlaby](https://github.com/BrianSlaby)

**Comment by MatthewNeie** [comment]
**Name:**
Matthew Neie

**Role:**
Web Developer

**Photo:**
will add later

**LinkedIn Profile:**
(https://www.linkedin.com/in/matthew-neie/)

**GitHub Profile:**
(https://github.com/MatthewNeie)

**Comment by MatthewNeie** [comment]
![Photo](https://github.com/chingu-voyages/v49-tier2-team-18/assets/132638527/52a2d1d1-642e-4c9e-b2b6-b1ff1fcc863b)

**Comment by BrianSlaby** [comment]
I filled in any missing info, Jonathan and Sushmita currently have blank/default profile pic placeholder images.
