### ISSUE TITLE
color picker material media fix

### ISSUE THREAD

**Issue by MatthewNeie** [chingu-voyages/v49-tier2-team-18#69]
**__Task Description__**
Describe the task to be completed.

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by BrianSlaby** [comment]
I reviewed, merged, and tested the PR that resolved this issue.  Everything looks good now!
